name: Delete Resource Group
on:
  workflow_dispatch:
  #schedule:
    #- cron: '0 0 * * *' # Runs at midnight every day

jobs:
  delete-resources:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Delete Resource Group
      uses: azure/powershell@v1
      with:
        inlineScript: |
          $rg= "webapps3-dev-rg" |
          $tagname = "Action" |
          $TagValue ="Delete" |
          Get-AzResource -TagName $tagname -TagValue $TagValue | where{$_.resourcegroupname -eq $rg}| Remove-AzResource -force
        azPSVersion: "latest"
