name: Delete Resource Group
on:
  workflow_dispatch:
  #schedule:
    #- cron: '0 0 * * *' # Runs at midnight every day
env:
  rg: 'webapps3-dev-rg' 
  tagname : 'Action'
  TagValue: 'Delete'

jobs:
  delete-resources:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Delete Resource Group
      uses: azure/cli@v1
      with:
        azcliversion: '2.0.72'
        inlineScript: |
          az resource delete -TagName ${{ env.tagname}} -TagValue ${{ env.TagValue}}| where{$_.resourcegroupname -eq ${{ env.rg}}}| az resource delete
