# This is a basic workflow to help you get started with Actions
name:  Deploy template to create the virtual networks and virtual machines in the different regions

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  DeployArmTemplate:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Azure Login
        uses: Azure/login@v1.4.2
        with:
          # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
          creds: ${{secrets.AZURE_CREDENTIALS}}
     
      - name: Deploy Azure Resource Manager (ARM) Template
        uses: Azure/arm-deploy@v1.0.8
        with:
         # Provide the scope of the deployment. Valid values are: 'resourcegroup', 'managementgroup', 'subscription'
         scope: resourcegroup
         
         # Override the Subscription Id set by Azure Login.
         # subscriptionId: ${{secrets.Subsciption_Id}}
         
         region : ${{secrets.location1}}
         #region : ${{secrets.location2}}
         resourceGroupName: ${{secrets.rgname}}
         
         # Provide the name of a resource group, only required for resource Group deployments.
         #resourceGroupName: rgname
         
         # Specify the path or URL to the Azure Resource Manager template.
         template: ./scripts/az104-05-vnetvm-loop-template.json
         
         # Incremental (only add resources to resource group) or Complete (remove extra resources from resource group) or Validate (only validates the template).
         deploymentMode: Incremental
         
         # Supply deployment parameter values.
         parameters: ./scripts/az104-05-vnetvm-loop-parameters.json
